@startuml

package "src" {
  package "components" {
    package "api" {
      class Chatbot {
        +mainAgent(message: string, markdown: string, update_Bot_stream_func: function): Promise<string>
      }
    }
    package "chat" {
      class Chat {
        +messages: array
        +text: string
        +open: boolean
        +chatHistory: Array
        +onSendMessage: function
        +handleSend()
      }
    }
    package "graph" {
      class Graph {
        +markdown: string
        +useMarkmap()
      }
    }
    package "list" {
      class List {
        +addMode: boolean
      }
    }
    package "login" {
      class Login {
        +avatar: object
        +handleAvatar()
        +handleLogin()
      }
    }
    package "notification" {
      class Notification {
        +ToastContainer
      }
    }
  }
  
  class App {
    -markdown: string
    -chatHistory: Array
    -user: boolean
    +handleSendMessage(message: string, update_Bot_stream_func: function): Promise<string>
  }
  
  App --> Chat : enthält
  App --> Graph : enthält
  App --> List : enthält
  App --> Login : enthält
  App --> Notification : enthält
  App --> Chatbot : uses
  Chat --> Chatbot : uses
}

@enduml